name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x

    - name: Install dependecies
      run: npm install

    - name: Lit code
      run: npm run lint:ci

    - name: Run tests
      run: npm run test:ci

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: npm run test:coverage
